// TODO: REPLACE THIS WITH C++ CODE TO FIND BINDINGS IN SHADERS
#define WRKGRP_SIZE_X 8
#define WRKGRP_SIZE_Y 8

#define BIND_DISPLAY_TEXTURE 0

#define BIND_HEIGHTMAP 1
#define BIND_FLUXMAP 2
#define BIND_VELOCITYMAP 3 

#define BIND_WRITE_HEIGHTMAP 8 
#define BIND_WRITE_FLUXMAP 9 
#define BIND_WRITE_VELOCITYMAP 10
