#define WORLD_SCALE (0.66)
#define SED_LAYERS (2)

#define WRKGRP_SIZE_X 8
#define WRKGRP_SIZE_Y 8

#define BIND_DISPLAY_TEXTURE 0

#define BIND_HEIGHTMAP 1
#define BIND_FLUXMAP 2
#define BIND_VELOCITYMAP 3 
#define BIND_SEDIMENTMAP 4 

#define BIND_THERMALFLUX_C 5 
#define BIND_THERMALFLUX_D 6 

#define BIND_WRITE_HEIGHTMAP 7 
#define BIND_WRITE_FLUXMAP 8 
#define BIND_WRITE_VELOCITYMAP 9
#define BIND_WRITE_SEDIMENTMAP 10

#define BIND_WRITE_THERMALFLUX_C 11
#define BIND_WRITE_THERMALFLUX_D 12
